### PR TITLE
Updates to allow the API version values as part of the deployment

### PR DESCRIPTION
**Pull request by Gergues**
## Purpose
Adding the option for the api version string value as part of the chat setup 
added AZURE_OPENAI_VERSION as environment  variable for both the container and the app to use.

## Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by Gergues** [comment]
(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by Gergues** [comment]
I  have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by pamelafox** [comment]
We usually store the version in the code as our code is often dependent on particular features in the API. What's the use case where your code isn't dependent on the API version?
(It's similar to pinning Python SDKs, we know which versions this code works with)

**Comment by Gergues** [comment]
I noticed that I can have the same API (gpt 35) under the same name and with 2 versions / deployment apiversion

When I ran the code as-is this did not work for sure , as there were other features in the service response that did not map properly
I was able to see that when comparing the 2 versions (OPEN AI service swagger) .
You may not see this when you deploy one instance , but will see it as you deploy an instance today and another one in 3 month 

Thanks

**Comment by pamelafox** [comment]
I made some changes and merged, thanks!

**Pull request merged**
